# Generated by Django 5.0.7 on 2024-08-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_created_todoitem_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
