# Generated by Django 5.0.7 on 2024-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
