# Generated by Django 5.0.7 on 2024-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
